apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: dc-metro-map-dj1z
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dc-metro-map-dj1z
    app.kubernetes.io/part-of: appstudio
  name: dc-metro-map-dj1z
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: dc-metro-map-dj1z
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: dc-metro-map-dj1z
    spec:
      containers:
      - image: quay.io/qijing/release-e2e-deploy-tenant/appstudio/dc-metro-map-dj1z@sha256:3dc95252608b8544098c79b9f903b5634c311f4d51bf6abae7c977054a2415ab
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
